[package]
name = "sound-keyboard"
version = "0.1.0"
authors = ["FPG Schiba <CraftZockerLP@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.77"

[[bin]]
name = "sound-keyboard"
harness = false

[profile.release]
opt-level = "s"

[profile.dev]
debug = true
opt-level = "z"

[features]
default = []
experimental = ["esp-idf-svc/experimental"]

[dependencies]
log = "0.4"
esp-idf-svc = "0.52.1"
anyhow = "1.0" # Optional, but highly recommended for standard Rust error handling

[build-dependencies]
embuild = "0.33"