[package]
name = "sound-keyboard"
version = "0.1.0"
authors = ["FPG Schiba <CraftZockerLP@gmail.com>"]
edition = "2021"
resolver = "2"

[[bin]]
name = "sound-keyboard"
harness = false

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[profile.dev]
debug = true
opt-level = "z"

[dependencies]
# HAL + panic handler
esp-hal              = { version = "0.22", features = ["esp32s3"] }
esp-backtrace        = { version = "0.14", features = ["esp32s3", "panic-handler", "exception-handler", "println"] }
esp-println          = { version = "0.12", features = ["esp32s3", "log"] }
log                  = { version = "0.4",  default-features = false }

# Embassy async runtime
embassy-executor     = { version = "0.6",  features = ["task-arena-size-20480"] }
embassy-time         = { version = "0.3" }
embassy-sync         = { version = "0.6" }
embassy-futures      = { version = "0.1" }
esp-hal-embassy      = { version = "0.5",  features = ["esp32s3", "integrated-timers"] }

# USB HID
usb-device                     = { version = "0.3" }
usbd-human-interface-device    = { version = "0.5" }

critical-section = "1.1"
